### ISSUE TITLE
User annot save dashboard in private tenant

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard-module-kibana-multitenancy#14] opened 2018-06-13 15:50 UTC
Hi,

By default , the user can see the global as read only and the private tenant as RW.

But when I swtich to private tenant and try to save the dashboard , it says permission denied?

How can we configure a user to save his own dashboards and be able to read data from all other indices?

Visualization Editor: no permissions for [indices:data/write/index] and User [name=webprod, roles=[readall], requestedTenant=null]: [security_exception] no permissions for [indices:data/write/index] and User [name=webprod, roles=[readall], …

I have assigned him the readall role so that the user can read data from all indices.
Do I need to assign the role special permissions to write to his own kibana index?

How can I make a user and role , so that the user can read all the data from any index , and save/write to his kibana dashboards?

**Comment by floragunn** [comment] 2018-06-13 16:03
duplicate of https://github.com/floragunncom/search-guard/issues/507

**Closed as completed by floragunn** 2018-06-13 16:03 UTC
