### ISSUE TITLE
Can't import dashboard when multitenancy is enabled 

### ISSUE THREAD

**Issue by elarib** [floragunncom/search-guard-module-kibana-multitenancy#12] opened 2017-11-07 10:26 UTC
Hello,
 Kibana now (from 5.5.1) supports the full export of dashboards, which means, when they addded a new import/export api, it exports the dashboards, its related viz & its index-pattern to a json file.
 See https://github.com/elastic/kibana/pull/10858

 We used this api from 5.5.1 & it works. 
 Those days we're trying to install searchguard & use the multitenancy, but searchguard don't let us import the json file.
 In ES : 
`[2017-11-07T11:15:00,504][WARN ][c.f.s.c.PrivilegesInterceptorImpl] Unhandled kibana related request class org.elasticsearch.action.bulk.BulkRequest`

In Kibana : 
```
log   [10:15:30.492] [warning][process] Error: Cannot provide statusCode or message with boom error
    at Object.exports.assert (/Users/elarib/Documents/SearchGuard/kibana-5.6.3-darwin-x86_64/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.wrap (/Users/elarib/Documents/SearchGuard/kibana-5.6.3-darwin-x86_64/node_modules/boom/lib/index.js:96:10)
    at then.catch.err (/Users/elarib/Documents/SearchGuard/kibana-5.6.3-darwin-x86_64/src/core_plugins/kibana/server/routes/api/import/index.js:39:120)
```
With curl, It gives 

> {"statusCode":403,"error":"Forbidden","message":"Error: Unauthorized"}

If you're wondering how we use the api, please see https://github.com/elastic/kibana/pull/10858#issuecomment-327776207

Please note, that we disable the multitenancy from kibana.yml & sg_config.yml, and it works, but, as you know, if we enable it again, the users can't see the dasboards, nor the viz, nor the index-pattern, because we created before enabling the multitenancy 

Can you please check it ? 

Thank you

**Comment by floragunn** [comment] 2017-11-27 16:55
thx for reporting, we will look into this

**Comment by floragunn** [comment] 2017-11-27 16:57
pls report bugs for the kibana plugin here https://github.com/floragunncom/search-guard-kibana-plugin

**Comment by floragunn** [comment] 2017-12-03 12:06
@elarib Can you test if it works with Elasticsearch+Kibana 5.6.x ?

**Comment by floragunn** [comment] 2017-12-04 19:56
@elarib we cannot reproduce this with 5.5.1 or 5.6.x

**Comment by elarib** [comment] 2017-12-05 09:20
@floragunncom I ll check it today, and let you know.
Thank you

**Comment by elarib** [comment] 2017-12-05 16:25
@floragunncom 
Did you test to import & export it using the new API ?
Using Es & Kibana 5.6.3

We can Export dashboard easily :

`curl -XGET localhost:5601/api/kibana/dashboards/export?dashboard=[dashboard_uuid] > my-dashboards.json`

But the import give us an error :

`curl -u userWithRoleAdmin:password -XPOST localhost:5601/api/kibana/dashboards/import -H 'Content-type:application/json' -d @my-dashboards.json`

give us the error : `{"statusCode":403,"error":"Forbidden","message":"Error: Unauthorized"}`

So the reproduce the error: 
Install ES & Kibana 5.6.3 with Searchguard, add some dashboard & viz to tenant X, and try to export them, after that change the tenant to Y, and try to import them (even if you use admin, the error persiste )

**Comment by jochenkressin** [comment] 2017-12-13 15:28
Yes, we used the new APIs, but still unable to reproduce. Can you send us your kibana.yml configuration please? 

Some questions regarding your sample curl calls:

1. The first one is missing basic authentication, is that on purpose?
2. Both are missing the kbn-xsrf header, is that on purpose?
3. When you say "switch tenant to X and try to import them", what exactly are you referring to? Changing the tenant in Kibana GUI should have no effect on the tenant used in the curl call.

**Comment by floragunn** [comment] 2018-02-07 19:53
Fixed with v10 of the [Kibana](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22search-guard-kibana-plugin%22) plugin, released today.

**Closed as completed by floragunn** 2018-02-07 19:53 UTC
Labels: sg6
